[package]
name = "flatnav"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "flatnav"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.24.0"
numpy = "0.24.0"
num-traits = "0.2"
rand = "0.9.1"